---
- hosts: localhost
  connection: local
  tasks:
    - name: download nodejs
      get_url: url=https://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz dest=files

    - name: create node_modules dir
      file: path=files/node_modules state=directory

    - name: extract nodejs
      shell: chdir=files creates=files/node-v0.12.7-linux-x64 tar -xzf node-v0.12.7-linux-x64.tar.gz

    - name: install log.io via npm
      environment:
        PATH: "files/node-v0.12.7-linux-x64/bin:{{ ansible_env.PATH }}"
      shell: chdir=files creates=files/node_modules/log.io npm install log.io

    - name: create tar.gz of log.io
      shell: chdir=files creates=files/log.io_node_modules.tar.gz tar -czf log.io_node_modules.tar.gz node_modules
